apiVersion: v1
kind: Service
metadata:
  name: sv-iq
spec:
  ports:
  - port: 5201
    protocol: TCP
    targetPort: 5201
  selector:
    app: iq
---
apiVersion: v1
kind: Service
metadata:
  name: sv-subframe
spec:
  ports:
  - port: 5202
    protocol: TCP
    targetPort: 5201
  selector:
    app: subframe
