apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: host-sflow
        image: sflow/host-sflow:latest
        env:
          - name: COLLECTOR
            value: "sflow-rt-sflow"
          - name: SAMPLING
            value: "10"
          - name: NET
            value: "flannel"
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-sock
            readOnly: true
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
