apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURnVENDQW1rQ0ZCLzlxV1poL1JOQlRiODdiWVV1Snd6S2FYRGtNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1IMHgKQ3pBSkJnTlZCQVlUQWtKU01Rc3dDUVlEVlFRSURBSlNVekVNTUFvR0ExVUVCd3dEY0c5aE1RNHdEQVlEVlFRSwpEQVZWUmxKSFV6RU1NQW9HQTFVRUN3d0RTVTVHTVE0d0RBWURWUVFEREFWdVlXUmhiREVsTUNNR0NTcUdTSWIzCkRRRUpBUllXY21wdFlYSjBhVzV6UUdsdVppNTFabkpuY3k1aWNqQWVGdzB5TURFeU1qSXhPRFU1TlRKYUZ3MHkKTVRFeU1qSXhPRFU1TlRKYU1IMHhDekFKQmdOVkJBWVRBa0pTTVFzd0NRWURWUVFJREFKU1V6RU1NQW9HQTFVRQpCd3dEY0c5aE1RNHdEQVlEVlFRS0RBVlZSbEpIVXpFTU1Bb0dBMVVFQ3d3RFNVNUdNUTR3REFZRFZRUUREQVZ1CllXUmhiREVsTUNNR0NTcUdTSWIzRFFFSkFSWVdjbXB0WVhKMGFXNXpRR2x1Wmk1MVpuSm5jeTVpY2pDQ0FTSXcKRFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU9KaER3U1YwT1lUSEhhcmNaSjc3Y0RCU1pZMwp0eEN0RDh1MkZtbEx3WEx3TGx0Y1d1WllZN01mZ3o4NFduZTJ1amIzSWMxS1IyR3UrbjBUaThzaTBRZ0RVTGVpCnRkeWlMVGVrNElOMlE5M0dtNmtqN1ZxMEduMnh6YlJ1Q2VLYkswLy9vTlRud3dXK2xTeVNKZDNMMkFyQWF6eVAKbzZFYnpPWklYVEVocFBlMWRjSk95aWpQRWVZTndxMGdPYm1WU1RUcHk3bHg3bjlhRXBNRjNvKzk1NllFSkRMRApYZTJtcHliM1pVdlNYVmh0ZnRCVnpRN3N5Vmt4UmZyRFJNUkErckUwajRkNGNRMVJYbmVrM3VYSGoyOHl3MXEzCnpxbENucEQrbURXRGZkSjdXN2NQdXgrV3pFZEV0QUVtWnh2UE9WclRkZDBRRmo2Tk4yWEczU1g3a3k4Q0F3RUEKQVRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUx4WVk3TFZTcjNmNjZpcnNJeFJnalRHUjRFQzF1NndNa0FGMgpTTUI1d09JanFLTUYwVW9YbSs1Sjh6VWpCRXNlOVJFbTJHTXNaYUoxSWtIcmRaVVVqQVJoOXNaN29Jbi9VN0NnCnFvdGNrUFpRaG1CRlJIUW1UTFNyZk51MFIyWCtIUi9jci9XaWRrSHY3MG04L0I1MmNlRjUva3NEbm03aC9GV20KOGo0cEV4aENZQmVYc1JiN3lCSUFSb0E5UC8yeVVoLzc2cDRibHhmSG0yeVV0Y3RzZHJKVmFIb0ZVY2ZoZFpmTQpaL0RtNU1uNFBXelVnSXFjSWMwZER4ZkpxZUpjLzVybFRtOUZwWFlxb3FGZG5vZ2x5clJBM3NZb28va3p0MUJmCjdVbktzemI3VWpGMHRiNDk0VjRBeXhqMjdNZ2tPdnl4Vi8wd1hqclpnbDN3SUJxNWRRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRGlZUThFbGREbUV4eDIKcTNHU2UrM0F3VW1XTjdjUXJRL0x0aFpwUzhGeThDNWJYRnJtV0dPekg0TS9PRnAzdHJvMjl5SE5Ta2RocnZwOQpFNHZMSXRFSUExQzNvclhjb2kwM3BPQ0Rka1BkeHB1cEkrMWF0QnA5c2MyMGJnbmlteXRQLzZEVTU4TUZ2cFVzCmtpWGR5OWdLd0dzOGo2T2hHOHptU0YweElhVDN0WFhDVHNvb3p4SG1EY0t0SURtNWxVazA2Y3U1Y2U1L1doS1QKQmQ2UHZlZW1CQ1F5dzEzdHBxY205MlZMMGwxWWJYN1FWYzBPN01sWk1VWDZ3MFRFUVBxeE5JK0hlSEVOVVY1MwpwTjdseDQ5dk1zTmF0ODZwUXA2US9wZzFnMzNTZTF1M0Q3c2Zsc3hIUkxRQkptY2J6emxhMDNYZEVCWStqVGRsCnh0MGwrNU12QWdNQkFBRUNnZ0VCQUxqQ1htOXZscjh3ZWRxZ3NtRExwSS9kTVNIWTl5QTFIdDgwRGJhQ2piQXgKTnFSNkMvWlR6WXN6L1Bwc0Urb0F5SnB6dUxMRUhONHM0V09Ud0ZSYVppQVVGSnpMdjRJREdzUi9YSDN1MkJUNQpNN0lvRUdBbS9qZjRGZHRjczlTdXIvcnF0MmtNZnE4QmpONkRxVVFNU3BiNzFJbm84Yk5iN1M5RmdFbkpHOHJPClZhU210UVMxdFRQMUd2VzZCa1ovY3QyeGc4aUc5Y3BGbUFJTnpkdVlPdEJwYys4dG1uUUlralBUdUZXYVhSMG4KM3RvQVN5SXlmeEZzWTVZZ2t5OTNmOXZSR1UyV0h5dGgycHJtejltZjIwWHcyblR6YmpZeXN1L2pzVWhLaEUxUgowY3VIQ2x6Smp1bTVPMFRwdjh3OFZnM3FPYzNaRklRNHFNSXltVWNpdEFFQ2dZRUErN3VFaWFyQnVWNWxrd1Q1CnBBbWxQMEFJY3BLWnJ3ZDhQQURBUGgyYVlDL0E5bU5wUHRSazlSVGYwWXI4b2phc2FZTTZWWHhVdHIwUHR6T1IKTkZoRHd5UUJXRkNKWGNtd0Z5M3VGbVN3dlBhek1UWWhtb1p0YURPWHFiYkx6ODlOVmVnWnZxM0pOcWlaRVk5Ywo4OVZYdE9xUTlrUXF0SEdYVE5NTWlVZDFDS0VDZ1lFQTVqZUMxY1BEWnBMdzhMd0pnUlhWNFlsL1BxOHR0NGxaCk1iMDBVZy9JbWJrRW1BOE91UU13RFlXZXJkSmJ1cmFGY3JlaG0yWXdyN3FoZnRaOXdWRVBJN08yMUNFSkRQcEQKY1IxeDl2d211aGRXNS9XQVhTTEFmaHNoWkt5SC9PMC95d0poQTR4SHZ5K1g3aHpDNnlycTFTM2RpQ0tsV2dDcQpDc0t3Rm52VitjOENnWUJLRUVmVWdVcnlFUlh0aFo4MVppa2FUT3F2V3ZhZ2lxRkF2aS9SbHNBZTRLM3pVQmhkCkJmeVdKd2diREx0N3RuNVBwTzU2ekZQWVdCUFJvUGh0NERJL3JjNC9mNktLMTVaWm00ZmJTdEM5S0JCY3dFSnUKeG5KV0lDZlZKUlVlRlMzNXdvb2drZDBMbWRzL1VXRFYxTVV6VTNoSEhKTTc5OWUrSUxJbGljS2pRUUtCZ0JWaQp3cnlvMnRZRWdHMWNpbVY3YWNyeHd1aEh6YTluQ3VvYjhXaE9Id3hvcTR5VW1ZR0dVa2h2U1RaTWZFanorNkdVCmZXYTZMM3Vqa3F6OXIrRHRic0thUnptZGVBSEVuYzg4TlFJRW1uUmZCcXUxbXA4TVEyVnpqNzZTYUcrT2VvYVoKU2ZuU1pqZlViQUNxbTFETlE5TloxMkoyRlhZdTZaem1TUVZOcTZyeEFvR0JBTkh5cVFFWkhwdm5PYnJ6aGw0WgpMSjZSb2c4ejN3RmJpYWZQenFGeTB5THZaUHhURkttRjNVbXlDakxNWnpieGI5d2pVVkhqSXEzc1hMbzJMWGdwCnpsbnBJM0V3cURNaXd1SzkwNFZwZjN0TFVQOERyZXRJYWkwR3Y5MWFZWDZadXpiRHFOWTFNVXhEem5JMStVNVcKbUFmUDM5bkU1V3VCVjlBZE5seEFFNE9hCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: nginx-with-ssl
        image: nginx
        ports:
        - containerPort: 443
          protocol: TCP
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/
        - name: nginx-tls
          mountPath: /etc/nginx-tls
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.8
        ports:
        - containerPort: 8080
      volumes:
      -  name: nginx-tls
         secret:
           secretName: secret-tls
      -  name: nginx-config-volume
         configMap:
           name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 443
  selector:
    app: hello-kubernetes
